<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empleados [
    <!ELEMENT empleados (empleado+)>
    <!ELEMENT empleado (nombre, edad)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT edad (#PCDATA)>

    <!ATTLIST empleado 
        sexo (y | h) #REQUIRED
        sueldo CDATA #IMPLIED
    >   
]>
<empleados>
    <empleado sexo="y" sueldo="1800">
        <nombre>Alberto Ruiz</nombre>
        <edad>56</edad>
    </empleado>

    <empleado sexo="h" sueldo="1600">
        <nombre>Gloria Martine</nombre>
        <edad>35</edad>
    </empleado>
</empleados>
