<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaclientes[
    <!ELEMENT listaclientes (cliente+)>  
    <!ELEMENT cliente (nombre, diasentrega+)>    
    <!ELEMENT nombre (#PCDATA)>    
    <!ELEMENT diasentrega (#PCDATA)>    
    <!ATTLIST cliente cif CDATA #REQUIRED>     
]>                                                                                                                  

<listaclientes>
    <cliente cif="567443">
        <nombre>Mercasa</nombre>
        <diasentrega>Lunes</diasentrega>
        <diasentrega>Martes</diasentrega>
    </cliente>

    <cliente cif="512155">
        <nombre id="especial">Acer SL</nombre>
        <diasentrega>Lunes</diasentrega>
        <diasentrega>Jueves</diasentrega>
    </cliente>
</listaclientes>