=== javiiiromeroo06/1DAM_LMSG_Javi/TEMA 11/Ejemplo5/concesionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"></xs:schema>
    <xs:element name = "concesionario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "coche" maxOccurs = "0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "marca" type = "xs.string"></xs:element>
                            <xs:element name = "modelo" type = "xs.string"></xs:element>
                            <xs:choice>
                                <xs:element name = "cilindrada" type = "xs:decimal"></xs:element>
                                <xs:element name = "caballos" type = "tipocaballo"></xs:element>
                            </xs:choice>
                            <xs:element name = "combustible" type = "tipocombustible"></xs:element>
                            <xs:element name = "precio" type = "xs.string"></xs:element>
                            <xs:element name = "año" type = "tipoaño"></xs:element>
                            <xs:element name = "color" type = "xs.string"></xs:element>
                            <xs:element name = "interesado" type = "tipointeresado" minOccurs = "0" maxOccurs = "unbounded"></xs:element>
                            <xs:element name = "accesorios" type = "tipoaccesorios" minOccurs = "0"></xs:element>
                        </xs:sequence>
                        <xs:attribute name = "matricuñas" type = "xs.string" use = "required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name = "provincia" type = "xs:string"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="tipocombustible">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Diesel"></xs:enumeration>
            <xs:enumeration value="Gasolina"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipocaballo">
        <xs:restriction base="xs:unsignedShort">
            <xs:minInclusive value = "60"></xs:minInclusive>
            <xs:maxInclusive value = "180"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

    <!-- Año de 4 cifras -->
     <xs:simpleType name="tipoaño">
        <xs:restriction base="xs:unsignedShort">
            <xs:totalDigits value = "4"></xs:totalDigits>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipodni">
        <xs:restriction base="xs:string">
            <xs:pattern value = "\d{8}[A-Z]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoaccesorios">
        <xs:list itemType="xs:string"></xs:list>
    </xs:simpleType>

    <xs:simpleType name="tresaccesorios">
        <xs:restriction base="tipoaccesorios">
            <xs:maxLenght value = "3"></xs:maxLenght>
        </xs:restriction>
    </xs:simpleType>
</:schema>

=== javiiiromeroo06/1DAM_LMSG_Javi/TEMA 11/Ejemplo5/concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<concesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="concesionario.xsd" provincia="Malaga">
    <coche matricula="6732KPC">
        <marca>Seat</marca>
        <modelo>Ateca</modelo>
        <cilindrada>1.7</cilindrada>
        <combustible>Diesel</combustible>
        <precio>23.000€</precio>
        <año>2018</año>
        <color>negro</color>
        <interesado>33358697A</interesado>
        <interesado>33628697A</interesado>
        <accesorios></accesorios>
    </coche>
    <coche matricula="7777JRC">
        <marca>BMW</marca>
        <modelo>Serie 1</modelo>
        <cilindrada>2.0</cilindrada>
        <combustible>Diesel</combustible>
        <precio>35.000€</precio>
        <año>2021</año>
        <color>azul</color>
        <interesado>34858697A</interesado>
    </coche>
    <coche matricula="6732KPC">
        <marca>Renault</marca>
        <modelo>Megane</modelo>
        <caballos>120</caballos>
        <combustible>Diesel</combustible>
        <precio>7.000€</precio>
        <año>2018</año>
        <color>verde</color>
    </coche>
</concesionario>
